version: 2.0
jobs:
  build:
    working_directory: ~/codezine-circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout
      
      - restore_cache:
        keys:
        - v1-rails-demo{{ checksum "Gemfile.lock"}}
        - vi-rails-demo
      - run: bundle install --path vendor/bundle
  
      - save_cache:
        keys:
        - vi-rails-demo{{ checksum "Gemfile.lock"}}
        paths:
          - vendor/bundle
          
      - run:
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run: bundle exec rspec
      
